apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "devops202607",
          "password": "<GITHUB_TOKEN>",
          "auth": "<base64(username:token)>"
        }
      }
    }
